POST http://127.0.0.1:8000/api/reset-password
Content-Type: application/json
Accept:  application/json

{
    "email": "edwin@example.com"
}


###cambio de contraseña
POST http://127.0.0.1:8000/api/change-password
Content-Type: application/json
Accept:  application/json

{
    "token":"30861b04f81d5e48af636f5928278ae184689a63dc9ca673fd90794a92fc5aa3",
    "email":"edwin@example.com",
    "password":"edwin12345",
    "password_confirmation":"edwin12345"
}
